
Parameters:
  ZBLambDummyDeliveryStreamBucket:
    Type: String
    AllowedPattern: arn:.*
    Description: A dummy S3 bucket ARN. The bucket will not be handelded with, it's just because of requirements.
  ZBLambPrivSubnet:
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: A private subnet. Must belong to ZBLambVPC.
  ZBLambVPC:
    Type: AWS::EC2::VPC::Id
    Description: The VPC under which to run the instances.
    ConstraintDescription: Must have a private AND a public subnet

Resources:
# Lambdas

  ZBLambFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Lambda function IAM role
        - Key: Description
          Value: IAM role of monitored Lambda functions allowing some operations for CloudWatch

  ZBLambMockLambda1:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: ZBLambMockLambda1
      Description: |
        Lambda function that passes or fails on demand.
        Input: { 'result': 'pass' / 'raise' / 'fail' / 'timeout' }
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            todo = event.get('result')
            if todo == 'pass':
              return "passed"
            if todo == 'raise':
              raise Exception('raised')
            if todo == 'timeout':
              from time import sleep
              sleep(5)
            exit(1)
      Handler: index.lambda_handler
      Runtime: python3.10
      Timeout: 2
      Role: !GetAtt ZBLambFunctionRole.Arn
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Mock Lambda function
        - Key: Description
          Value: A sample lambda function to monitor via Zabbix. Successful call or type of failure can be invoked in the event argument.


  ZBLambZabbixSecGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Zabbix access
      VpcId: !Ref ZBLambVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 10050
          ToPort: 10050
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 10051
          ToPort: 10051
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Zabbix security group
        - Key: Description
          Value: EC2 security group allowing connections to ports 10050 and 10051 from parametrized IP CIDR range

  ZBLambMetricStreamTransformLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ZBLambFirehoseTransform
      Role: !GetAtt ZBLambFunctionRole.Arn
      Runtime: python3.10
      Handler: index.lambda_handler
#      Environment:
#        Variables:
#          ZBLAMB_PROXY_IP: !GetAtt ZBLambZabProxy.PrivateIp
      Code:
        ZipFile: |
          import json, struct, socket, base64, os, itertools as i
          def lambda_handler(e,c):
             n,h,k,v,t,F,D,R = "zabbix-lambda-errors", "host", "key", "value", "timestamp", "FunctionName","dimensions", e['records']
             print(e)
             return {'records': [{'recordId': r['recordId'],'result': 'Dropped','data': ''} for r in R]}

             for j in i.chain(*[ list(filter(lambda j: list(j[D].keys())==[F],map( json.loads,base64.b64decode(r['data']).decode('utf-8').splitlines() )))  for r in R]): 
               V, N=int(j[v]['sum']), j[D][F]
               d = json.dumps({"request":"sender data","data": [
                *([ { h:n,k:"error-stream",v:N } ] * V),
                {h:n,k:"error-log",v:f"ERROR {V} {N}"},
                {h:n,k:"error-counts",v:f"{V}"},
                {h:n,k:"error-count-string",v:','.join([N]*V)}],
                "clock":j[t] }).encode("utf-8")
               #s=socket.create_connection((os.env['ZBLAMB_PROXY_IP'],10051))
               #s.sendall(b"ZBXD\1" + struct.pack("<II",len(d),0) + d)
               #print(s.recv(1024))
               #s.close()
               print(b"ZBXD\1" + struct.pack("<II",len(d),0) + d)
             return {'records': [{'recordId': r['recordId'],'result': 'Dropped','data': ''} for r in R]}
      VpcConfig:
        SubnetIds:
          - !Ref ZBLambPrivSubnet
        SecurityGroupIds:
          - !Ref ZBLambZabbixSecGroup
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Firehose stream transformation
        - Key: Description
          Value: Lambda function used to transform Firehose metric stream and send it to Zabbix Proxy


  ZBLambMetricStreamFirehoseIAM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement: [{
              "Sid": "",
              "Effect": "Allow",
              "Principal": {
                "Service": "firehose.amazonaws.com"
              },
              "Action": "sts:AssumeRole",
          }]
      Path: "/"
      Policies:
      - PolicyName: FirehorseToS3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement: [{      
                    "Effect": "Allow",      
                    "Action": [
                        "s3:AbortMultipartUpload",
                        "s3:GetBucketLocation",
                        "s3:GetObject",
                        "s3:ListBucket",
                        "s3:ListBucketMultipartUploads",
                        "s3:PutObject"
                    ],      
                    "Resource": [        
                        "Ref": "ZBLambDummyDeliveryStreamBucket",
                        "Fn::Sub": "${ZBLambDummyDeliveryStreamBucket}/*"
                    ]    
                },        
                {
                    "Effect": "Allow", 
                    "Action": [
                        "lambda:InvokeFunction", 
                        "lambda:GetFunctionConfiguration" 
                    ],
                    "Resource": [
                        "Fn::GetAtt": [ "ZBLambMetricStreamTransformLambda", "Arn" ]
                    ]
              }]
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Mock Lambda function IAM role
        - Key: Description
          Value: IAM role of monitored Lambda functions allowing some operations for CloudWatch

  ZBLambMetricStreamFirehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamType: DirectPut
      ExtendedS3DestinationConfiguration:
        BucketARN: !Ref ZBLambDummyDeliveryStreamBucket
        BufferingHints:
          IntervalInSeconds: 0 # 300 # 5 min
        CloudWatchLoggingOptions:
          Enabled: false
        CompressionFormat: UNCOMPRESSED
        EncryptionConfiguration: 
          NoEncryptionConfig: "NoEncryption"
        S3BackupMode: "Disabled"
        RoleARN: !GetAtt ZBLambMetricStreamFirehoseIAM.Arn

        ProcessingConfiguration:
          Enabled: true
          Processors:
            - Type: Lambda
              Parameters: 
                - ParameterName: LambdaArn
                  ParameterValue: !GetAtt ZBLambMetricStreamTransformLambda.Arn
                #- ParameterName: BufferIntervalInSeconds
                #  ParameterValue: "1"
                #- ParameterName: BufferSizeInMBs
                #  ParameterValue: "1"
                - ParameterName: CompressionFormat
                  ParameterValue: UNCOMPRESSED
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Metric Delivery Stream
        - Key: Description
          Value: The Firehose stream that streams metrics from CloudWatch to the S3 bucket / HTTP Endpoint

  ZBLambMetricStreamIAM:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - streams.metrics.cloudwatch.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: FirehoseAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - firehose:PutRecord
            - firehose:PutRecordBatch
            Resource: !GetAtt ZBLambMetricStreamFirehose.Arn
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Metric Stream IAM permission
        - Key: Description
          Value: IAM role of the metric stream to access the Firehose
 
  ZBLambMetricStream:
    Type: AWS::CloudWatch::MetricStream
    Properties:
      FirehoseArn: !GetAtt ZBLambMetricStreamFirehose.Arn
      RoleArn: !GetAtt ZBLambMetricStreamIAM.Arn
      OutputFormat: json
      IncludeFilters:
        - Namespace: "AWS/Lambda"
          MetricNames: [ "Errors" ]
      Tags:
        - Key: Name
          Value: Zabbix Lambda monitor Metric Stream 
        - Key: Description
          Value: The metric stream used to push AWS/Lambda Errors to Lambda pushing to Zabbix