services:
  zblamb-zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-5.4-latest
    restart: always
    environment:
      - ZBX_HOSTNAME=zblamb-agent
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
    ports:
      - "10050:10050"
    init: true

  zblamb-sample-app:
    image: nginxdemos/nginx-hello:plain-text
    restart: always
    ports:
      - "80:8080"
    
