services:
  zblamb-zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-5.4-latest
    restart: always
    environment:
      - ZBX_PROXYMODE=1 # passive proxy
      - ZBX_HOSTNAME=zblamb-proxy
    ports:
      - "10051:10051"
    init: true

