services:
  zblamb-postgres:
    image: postgres:13-alpine
    restart: always
    networks:
     zab-serv-net:
      aliases: ["postgres-server"]
    env_file:
      - .env

  zblamb-zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-5.4-latest
    restart: always
    networks:
      zab-serv-net:
        aliases: ["zabbix-server"]
    ports:
      - "10051:10051"
    init: true
    depends_on:
      - zblamb-postgres
    env_file:
      - .env
    
  zblamb-zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-5.4-latest
    restart: always
    networks:
      - zab-serv-net
    ports:
     - "80:8080"
     - "443:8443"
    depends_on:
      - zblamb-zabbix-server
    env_file:
      - .env

networks:
  zab-serv-net: